services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: |
      apt-get update && 
      apt-get install -y libgtk-4.1 libgraphene-1.0 libgstreamer-gl1.0-0 libavif15 libenchant-2-2 libsecret-1-0 libmanette-0.2-0 libgles2 &&
      npm install --omit=dev &&
      npx playwright install chromium &&
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
