services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install && npx playwright install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
